# Global

stages:
  - Platform Tests
  - Analysis

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CTEST_OUTPUT_ON_FAILURE: '1'

# Platform Tests

.platform_unix_template: &platform_unix_template
  stage: Platform Tests
  tags:
    - docker-linux
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

.platform_windows_template: &platform_windows_template
  stage: Platform Tests
  image: docker.io/stabletec/build-foe:windows
  tags:
    - docker-windows
    - amd64
  script:
    - mkdir build; cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ninja test

.platform_macos_template: &platform_macos_template
  stage: Platform Tests
  tags:
    - macos
    - amd64
  dependencies: []
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

Arch/GCC:
  image: docker.io/stabletec/build-foe:arch
  variables:
    CC: gcc
    CXX: g++
  <<: *platform_unix_template

Arch/Clang:
  image: docker.io/stabletec/build-foe:arch
  variables:
    CC: clang
    CXX: clang++
  <<: *platform_unix_template

Fedora/GCC:
  image: docker.io/stabletec/build-foe:fedora
  variables:
    CC: gcc
    CXX: g++
  <<: *platform_unix_template

Fedora/Clang:
  image: docker.io/stabletec/build-foe:fedora
  variables:
    CC: clang
    CXX: clang++
  <<: *platform_unix_template

Ubuntu/GCC:
  image: docker.io/stabletec/build-foe:ubuntu
  variables:
    CC: gcc
    CXX: g++
  <<: *platform_unix_template

Ubuntu/Clang:
  image: docker.io/stabletec/build-foe:ubuntu
  variables:
    CC: clang
    CXX: clang++
  <<: *platform_unix_template

Debian 10/GCC (Old v97):
  image: docker.io/stabletec/build-core:debian-10
  variables:
    CC: gcc
    CXX: g++
  stage: Platform Tests
  tags:
    - docker-linux
  script:
    - apt install -y libvulkan-dev
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

Debian 10/Clang (Old v97):
  image: docker.io/stabletec/build-core:debian-10
  variables:
    CC: clang
    CXX: clang++
  stage: Platform Tests
  tags:
    - docker-linux
  script:
    - apt install -y libvulkan-dev
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

Windows/MSVC:
  <<: *platform_windows_template

Windows/Clang-cl:
  variables:
    CC: clang-cl
    CXX: clang-cl
  <<: *platform_windows_template

macOS/Clang (amd64):
  variables:
    CC: clang
    CXX: clang++
  <<: *platform_macos_template

# Analysis
Code Coverage:
  stage: Analysis
  image: docker.io/stabletec/build-foe:arch
  tags:
    - docker-linux
  dependencies: []
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCODE_COVERAGE=ON -DBUILD_TESTS=ON
    - ninja
    - ninja ccov-VkSerializationTests
    - ninja ccov-report-VkSerializationTests
  artifacts:
    name: CodeCoverage
    paths: 
      - build/ccov
    expire_in: 1 day

.analysis_template: &analysis_template
  stage: Analysis
  image: docker.io/stabletec/build-foe:arch
  tags:
    - docker-linux
  dependencies: []
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ${CMAKE_OPTIONS}
    - ninja
    - ninja test

AddressSanitizer:
  variables:
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DUSE_SANITIZER=Address
  <<: *analysis_template

LeakSanitizer:
  variables:
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DUSE_SANITIZER=Leak
  <<: *analysis_template

UndefinedSanitizer:
  variables:
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DUSE_SANITIZER=Undefined
  <<: *analysis_template